### ISSUE TITLE
Trying to get JSON from AST without compiling in Solidity.

### ISSUE THREAD

**Issue by Ethnical** [Ethnical/Swek3#2]
The goal here is to try to get JSON from the AST using `ethers-rs`. 
So to do that,  I modified the `ethers-rs` lib by adding the function `get_data` here (I don't think this is the best option here to do, but for now it works) => 
[get_data()](https://github.com/gakonst/ethers-rs/blob/a9dd53da810d8eff82aa77e0f9297b4a453028e6/ethers-solc/src/resolver/mod.rs#L869)
 
```rust
 impl Node {
    /// Reads the content of the file and returns a [Node] containing relevant information
    pub fn read(file: impl AsRef<Path>) -> Result<Self> {
        let file = file.as_ref();
        let source = Source::read(file).map_err(|err| {
            if !err.path().exists() && err.path().is_symlink() {
                SolcError::ResolveBadSymlink(err)
            } else {
                SolcError::Resolve(err)
            }
        })?;
        let data = SolData::parse(source.as_ref(), file);
        Ok(Self { path: file.to_path_buf(), source, data })
    }

    pub fn content(&self) -> &str {
        &self.source.content
    }

    pub fn imports(&self) -> &Vec<SolDataUnit<SolImport>> {
        &self.data.imports
    }

    pub fn version(&self) -> &Option<SolDataUnit<String>> {
        &self.data.version
    }

    pub fn experimental(&self) -> &Option<SolDataUnit<String>> {
        &self.data.experimental
    }

    pub fn license(&self) -> &Option<SolDataUnit<String>> {
        &self.data.license
    }

    pub fn unpack(&self) -> (&PathBuf, &Source) {
        (&self.path, &self.source)
    }
    pub fn get_data(&self) -> &SolData { //here the get_data to get back the SolData and then try to walk it.
        &self.data
    }
}
```

So now using [get_data](https://github.com/Ethnical/Swek3/blob/e666e3cb6d7d914131e2658e06541be3d0475a56/src/modifiers.rs#L46), we can  walk over the object `SolContract` but for some compatibilities and sharing purposes in the future would like to get a JSON output (Think you could use Deserialize stuffs over all the type but didn't succed)

The final is to get output exactly like this project from ConsenSys written in Python => https://github.com/ConsenSys/python-solidity-parser

So for the moment, I am able to work on the AST(Rust object) but would like to find a way to convert it into JSON or find a way to get JSON directly.

**Comment by DemesneGH** [comment]
Hi @Ethnical 

> So now using [get_data](https://github.com/Ethnical/Swek3/blob/e666e3cb6d7d914131e2658e06541be3d0475a56/src/modifiers.rs#L46), we can walk over the object `SolContract`

From my understanding: 
After modifying the source code of `ether-rs`, the json can be dumped manually in `Sweb3` tool, by these lines of code :
https://github.com/Ethnical/Swek3/blob/e666e3cb6d7d914131e2658e06541be3d0475a56/src/modifiers.rs#L46-L70.

So you want a workaround for outputting the JSON of class `SolData` without modification of `ether-rs`, right?

**Comment by Ethnical** [comment]
@DemesneGH Yep exactly! if we could convert instantly `SolData` will be perfect! Like in the Consensys tool :)

**Comment by DemesneGH** [comment]
@Ethnical 
Is it necessary to use the `ether-rs` crate? Have you tried other crates which act like a 'rust-solidity-parser'?

**Comment by Ethnical** [comment]
No, this library is not mandatory ahah if we find another alternative could be nice! 
For `rust-solidity-parser` tried quickly but didn't succeed to have a JSON AST output. 
But if you have any leads feel free to share them with me! :)

**Comment by DemesneGH** [comment]
@Ethnical 
I did a quick search and not found a crate as `rust-solidity-parser`. But in this crate (https://github.com/camden-smallwood/solidity-rs) the structs can be serialized, eg: https://github.com/camden-smallwood/solidity-rs/blob/1b6c0cf2da7a72026a775548a8585b93c325a126/solidity/src/ast/source_units.rs#L6

When converting a `struct` to `JSON` we often use `serde_json` crate, and add `#[derive(Serialize, Deserilaize)]` macro before the struct we defined. Then invoking `serde_json::to_string(Structure-To-Be-Serialized)` in your code will generate json format as string.

BTW, the alternative is to add `#[derive(Serialize, Deserilaize)]` macro for `SolData` and its child types such as `SolDataUnit`, etc. https://github.com/gakonst/ethers-rs/blob/cffcc7bbec2f34bc0b11a522d374b816587070e4/ethers-solc/src/resolver/parse.rs#L13-L23. But it needs some modification on the `ether-rs` crate.

**Comment by Ethnical** [comment]
Hey @DemesneGH, 
Still working on it made the first PR here => https://github.com/hyperledger/solang/pull/1055
Now, need to make a new PR for `ethers-solc` will keep you posted!
